# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\components_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_uiComponentsPage(object):
    def setupUi(self, uiComponentsPage):
        uiComponentsPage.setObjectName("uiComponentsPage")
        uiComponentsPage.resize(1020, 668)
        self.horizontalLayout = QtWidgets.QHBoxLayout(uiComponentsPage)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiView = QtWidgets.QTreeView(uiComponentsPage)
        self.uiView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.uiView.setIconSize(QtCore.QSize(25, 25))
        self.uiView.setIndentation(0)
        self.uiView.setAnimated(True)
        self.uiView.setObjectName("uiView")
        self.horizontalLayout.addWidget(self.uiView)

        self.retranslateUi(uiComponentsPage)
        QtCore.QMetaObject.connectSlotsByName(uiComponentsPage)

    def retranslateUi(self, uiComponentsPage):
        _translate = QtCore.QCoreApplication.translate
        uiComponentsPage.setWindowTitle(_translate("uiComponentsPage", "Form"))
