# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\settings_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settings_window(object):
    def setupUi(self, settings_window):
        settings_window.setObjectName("settings_window")
        settings_window.setWindowModality(QtCore.Qt.ApplicationModal)
        settings_window.resize(629, 475)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(settings_window)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(settings_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.uiImportBtn = QtWidgets.QPushButton(settings_window)
        self.uiImportBtn.setObjectName("uiImportBtn")
        self.horizontalLayout_7.addWidget(self.uiImportBtn)
        self.uiExportBtn = QtWidgets.QPushButton(settings_window)
        self.uiExportBtn.setObjectName("uiExportBtn")
        self.horizontalLayout_7.addWidget(self.uiExportBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.uiArchiveBox = QtWidgets.QGroupBox(settings_window)
        self.uiArchiveBox.setObjectName("uiArchiveBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.uiArchiveBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addWidget(self.uiArchiveBox)
        self.uiCustomizationBox = QtWidgets.QGroupBox(settings_window)
        self.uiCustomizationBox.setObjectName("uiCustomizationBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.uiCustomizationBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addWidget(self.uiCustomizationBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uiStatusBox = QtWidgets.QGroupBox(settings_window)
        self.uiStatusBox.setObjectName("uiStatusBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.uiStatusBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2.addWidget(self.uiStatusBox)
        self.uiManufactureBox = QtWidgets.QGroupBox(settings_window)
        self.uiManufactureBox.setObjectName("uiManufactureBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.uiManufactureBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_2.addWidget(self.uiManufactureBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.uiOkBtn = QtWidgets.QPushButton(settings_window)
        self.uiOkBtn.setObjectName("uiOkBtn")
        self.horizontalLayout_6.addWidget(self.uiOkBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)

        self.retranslateUi(settings_window)
        QtCore.QMetaObject.connectSlotsByName(settings_window)

    def retranslateUi(self, settings_window):
        _translate = QtCore.QCoreApplication.translate
        settings_window.setWindowTitle(_translate("settings_window", "Settings"))
        self.label.setText(_translate("settings_window", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Settings</span></p></body></html>"))
        self.uiImportBtn.setText(_translate("settings_window", "Import\n"
"Settings"))
        self.uiExportBtn.setText(_translate("settings_window", "Export\n"
"Settings"))
        self.uiArchiveBox.setTitle(_translate("settings_window", "Hardware Archive"))
        self.uiCustomizationBox.setTitle(_translate("settings_window", "Customization"))
        self.uiStatusBox.setTitle(_translate("settings_window", "Status Entries"))
        self.uiManufactureBox.setTitle(_translate("settings_window", "Manufacture Entries"))
        self.uiOkBtn.setText(_translate("settings_window", "Ok"))
        self.uiOkBtn.setShortcut(_translate("settings_window", "Esc"))
