# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_bill_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_uiBillPage(object):
    def setupUi(self, uiBillPage):
        uiBillPage.setObjectName("uiBillPage")
        uiBillPage.resize(1018, 718)
        self.horizontalLayout = QtWidgets.QHBoxLayout(uiBillPage)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiBillView = QtWidgets.QTableView(uiBillPage)
        self.uiBillView.setMinimumSize(QtCore.QSize(1000, 700))
        self.uiBillView.setAlternatingRowColors(True)
        self.uiBillView.setObjectName("uiBillView")
        self.horizontalLayout.addWidget(self.uiBillView)

        self.retranslateUi(uiBillPage)
        QtCore.QMetaObject.connectSlotsByName(uiBillPage)

    def retranslateUi(self, uiBillPage):
        _translate = QtCore.QCoreApplication.translate
        uiBillPage.setWindowTitle(_translate("uiBillPage", "Form"))
