# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_hardware_selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_uiHardwareEditor(object):
    def setupUi(self, uiHardwareEditor):
        uiHardwareEditor.setObjectName("uiHardwareEditor")
        uiHardwareEditor.setWindowModality(QtCore.Qt.ApplicationModal)
        uiHardwareEditor.resize(1110, 647)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(uiHardwareEditor)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.uiSelectQuantity = QtWidgets.QSpinBox(uiHardwareEditor)
        self.uiSelectQuantity.setMinimum(1)
        self.uiSelectQuantity.setObjectName("uiSelectQuantity")
        self.verticalLayout.addWidget(self.uiSelectQuantity)
        self.uiOkButton = QtWidgets.QPushButton(uiHardwareEditor)
        self.uiOkButton.setDefault(True)
        self.uiOkButton.setObjectName("uiOkButton")
        self.verticalLayout.addWidget(self.uiOkButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.uiMechanicalButton = QtWidgets.QPushButton(uiHardwareEditor)
        self.uiMechanicalButton.setCheckable(True)
        self.uiMechanicalButton.setChecked(True)
        self.uiMechanicalButton.setAutoExclusive(True)
        self.uiMechanicalButton.setObjectName("uiMechanicalButton")
        self.verticalLayout.addWidget(self.uiMechanicalButton)
        self.uiMeasuredButton = QtWidgets.QPushButton(uiHardwareEditor)
        self.uiMeasuredButton.setCheckable(True)
        self.uiMeasuredButton.setAutoExclusive(True)
        self.uiMeasuredButton.setObjectName("uiMeasuredButton")
        self.verticalLayout.addWidget(self.uiMeasuredButton)
        self.uiElectricalButton = QtWidgets.QPushButton(uiHardwareEditor)
        self.uiElectricalButton.setCheckable(True)
        self.uiElectricalButton.setAutoExclusive(True)
        self.uiElectricalButton.setObjectName("uiElectricalButton")
        self.verticalLayout.addWidget(self.uiElectricalButton)
        self.uiElectromechanicalButton = QtWidgets.QPushButton(uiHardwareEditor)
        self.uiElectromechanicalButton.setCheckable(True)
        self.uiElectromechanicalButton.setAutoExclusive(True)
        self.uiElectromechanicalButton.setObjectName("uiElectromechanicalButton")
        self.verticalLayout.addWidget(self.uiElectromechanicalButton)
        self.uiConsumableButton = QtWidgets.QPushButton(uiHardwareEditor)
        self.uiConsumableButton.setCheckable(True)
        self.uiConsumableButton.setAutoExclusive(True)
        self.uiConsumableButton.setObjectName("uiConsumableButton")
        self.verticalLayout.addWidget(self.uiConsumableButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.uiCancelButton = QtWidgets.QPushButton(uiHardwareEditor)
        self.uiCancelButton.setObjectName("uiCancelButton")
        self.verticalLayout.addWidget(self.uiCancelButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.uiViewContainer = QtWidgets.QVBoxLayout()
        self.uiViewContainer.setObjectName("uiViewContainer")
        self.uiSearchEntry = QtWidgets.QLineEdit(uiHardwareEditor)
        self.uiSearchEntry.setObjectName("uiSearchEntry")
        self.uiViewContainer.addWidget(self.uiSearchEntry)
        self.uiHardwareView = QtWidgets.QTableView(uiHardwareEditor)
        self.uiHardwareView.setAlternatingRowColors(True)
        self.uiHardwareView.setSortingEnabled(False)
        self.uiHardwareView.setObjectName("uiHardwareView")
        self.uiViewContainer.addWidget(self.uiHardwareView)
        self.horizontalLayout.addLayout(self.uiViewContainer)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(uiHardwareEditor)
        QtCore.QMetaObject.connectSlotsByName(uiHardwareEditor)

    def retranslateUi(self, uiHardwareEditor):
        _translate = QtCore.QCoreApplication.translate
        uiHardwareEditor.setWindowTitle(_translate("uiHardwareEditor", "Hardware Selector"))
        self.uiOkButton.setText(_translate("uiHardwareEditor", "Ok"))
        self.uiOkButton.setShortcut(_translate("uiHardwareEditor", "Return"))
        self.uiMechanicalButton.setText(_translate("uiHardwareEditor", "MEH"))
        self.uiMeasuredButton.setText(_translate("uiHardwareEditor", "MMH"))
        self.uiElectricalButton.setText(_translate("uiHardwareEditor", "ELH"))
        self.uiElectromechanicalButton.setText(_translate("uiHardwareEditor", "EMH"))
        self.uiConsumableButton.setText(_translate("uiHardwareEditor", "CON"))
        self.uiCancelButton.setText(_translate("uiHardwareEditor", "Cancel"))
        self.uiCancelButton.setShortcut(_translate("uiHardwareEditor", "Esc"))
        self.uiSearchEntry.setPlaceholderText(_translate("uiHardwareEditor", "Search..."))
