# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\entries_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_entries_list(object):
    def setupUi(self, entries_list):
        entries_list.setObjectName("entries_list")
        entries_list.resize(309, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(entries_list)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.uiAddBtn = QtWidgets.QPushButton(entries_list)
        self.uiAddBtn.setObjectName("uiAddBtn")
        self.gridLayout.addWidget(self.uiAddBtn, 1, 1, 1, 1)
        self.uiEntry = QtWidgets.QLineEdit(entries_list)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiEntry.sizePolicy().hasHeightForWidth())
        self.uiEntry.setSizePolicy(sizePolicy)
        self.uiEntry.setObjectName("uiEntry")
        self.gridLayout.addWidget(self.uiEntry, 1, 0, 1, 1)
        self.uiList = QtWidgets.QListView(entries_list)
        self.uiList.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.uiList.setAlternatingRowColors(True)
        self.uiList.setObjectName("uiList")
        self.gridLayout.addWidget(self.uiList, 0, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(entries_list)
        QtCore.QMetaObject.connectSlotsByName(entries_list)

    def retranslateUi(self, entries_list):
        _translate = QtCore.QCoreApplication.translate
        entries_list.setWindowTitle(_translate("entries_list", "Form"))
        self.uiAddBtn.setText(_translate("entries_list", "Add"))
        self.uiAddBtn.setShortcut(_translate("entries_list", "Return"))
