# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\archive_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_uiArchiveView(object):
    def setupUi(self, uiArchiveView):
        uiArchiveView.setObjectName("uiArchiveView")
        uiArchiveView.resize(1084, 728)
        self.horizontalLayout = QtWidgets.QHBoxLayout(uiArchiveView)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.uiSearchEntry = QtWidgets.QLineEdit(uiArchiveView)
        self.uiSearchEntry.setObjectName("uiSearchEntry")
        self.verticalLayout_2.addWidget(self.uiSearchEntry)
        self.uiView = QtWidgets.QTableView(uiArchiveView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiView.sizePolicy().hasHeightForWidth())
        self.uiView.setSizePolicy(sizePolicy)
        self.uiView.setMinimumSize(QtCore.QSize(1000, 700))
        self.uiView.setAlternatingRowColors(True)
        self.uiView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.uiView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.uiView.setObjectName("uiView")
        self.uiView.horizontalHeader().setHighlightSections(False)
        self.uiView.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.uiView)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.uiMEHBtn = QtWidgets.QPushButton(uiArchiveView)
        self.uiMEHBtn.setCheckable(True)
        self.uiMEHBtn.setChecked(True)
        self.uiMEHBtn.setAutoExclusive(True)
        self.uiMEHBtn.setObjectName("uiMEHBtn")
        self.verticalLayout.addWidget(self.uiMEHBtn)
        self.uiMMHBtn = QtWidgets.QPushButton(uiArchiveView)
        self.uiMMHBtn.setCheckable(True)
        self.uiMMHBtn.setAutoExclusive(True)
        self.uiMMHBtn.setObjectName("uiMMHBtn")
        self.verticalLayout.addWidget(self.uiMMHBtn)
        self.uiEMHBtn = QtWidgets.QPushButton(uiArchiveView)
        self.uiEMHBtn.setCheckable(True)
        self.uiEMHBtn.setAutoExclusive(True)
        self.uiEMHBtn.setObjectName("uiEMHBtn")
        self.verticalLayout.addWidget(self.uiEMHBtn)
        self.uiELHBtn = QtWidgets.QPushButton(uiArchiveView)
        self.uiELHBtn.setCheckable(True)
        self.uiELHBtn.setAutoExclusive(True)
        self.uiELHBtn.setObjectName("uiELHBtn")
        self.verticalLayout.addWidget(self.uiELHBtn)
        self.uiPROBtn = QtWidgets.QPushButton(uiArchiveView)
        self.uiPROBtn.setCheckable(True)
        self.uiPROBtn.setAutoExclusive(True)
        self.uiPROBtn.setObjectName("uiPROBtn")
        self.verticalLayout.addWidget(self.uiPROBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(uiArchiveView)
        QtCore.QMetaObject.connectSlotsByName(uiArchiveView)

    def retranslateUi(self, uiArchiveView):
        _translate = QtCore.QCoreApplication.translate
        uiArchiveView.setWindowTitle(_translate("uiArchiveView", "Form"))
        self.uiSearchEntry.setPlaceholderText(_translate("uiArchiveView", "Search..."))
        self.uiMEHBtn.setText(_translate("uiArchiveView", "MEH"))
        self.uiMMHBtn.setText(_translate("uiArchiveView", "MMH"))
        self.uiEMHBtn.setText(_translate("uiArchiveView", "EMH"))
        self.uiELHBtn.setText(_translate("uiArchiveView", "ELH"))
        self.uiPROBtn.setText(_translate("uiArchiveView", "PRO"))
